### PR TITLE
Fabric 1.19.2 Create 0.5.1-b

### PR DESCRIPTION
**Pull request by AlphaMode**
Initial Port haven't done testing yet

### CODE REVIEW

**Comment by AlphaMode** [comment]
I'll go ahead and mark this ready I haven't had time to test it but, I've heard from people from the community it seems to work. If any major issues occur I'll make a follow up PR.

**Comment by wanesty** [comment]
from my testing, everything is working

only computercraft haven't been tested yet but it should:tm: be working

**Review by mrh0 — APPROVED** [review]

**Comment by Hereux** [comment]
@wanesty @AlphaMode I'm using ComputerCraft and it doesn't work. mrh0 already knows about it and mistakenly closed my report. I opened a new one with a bit more information. Would be very nice if you find  some time for it soon 😅

https://github.com/mrh0/createaddition/issues/622

**Comment by wanesty** [comment]
@Hereux 
i'd suggest you try [CC:C Bridge](https://modrinth.com/mod/cccbridge) as a "replacement" until this get resolved

**Comment by Hereux** [comment]
> @Hereux i'd suggest you try [CC:C Bridge](https://modrinth.com/mod/cccbridge) as a "replacement" until this get resolved

Thanks for the fast response. I just had a quick look into the mod  and its documentation and if I saw it correctly, it has no function to get information from an create block and use it in the computer.

**Comment by wanesty** [comment]
yes, that's why i put replacement in quotes,
it is not one, but it's still a way to interface some create stuff to CC, this is the reason i mentioned it for

**Pull request merged**
