### PR TITLE
Update to 1.20.1 Fabric

### PR DESCRIPTION
**Pull request by skippyall**

### CODE REVIEW

**Comment by skippyall** [comment]
I found that the textures of the fluids don't load, however I don't know how to fix this

**Comment by mrh0** [comment]
For some reason this file was git ignored and never got commited, add this: https://github.com/mrh0/createaddition/blob/1.20.1/src/main/resources/assets/minecraft/atlases/blocks.json

**Comment by skippyall** [comment]
Should all be working now. Thank you!

**Review by mrh0 — APPROVED** [review]

**Comment by mrh0** [comment]
Not able to test, getting this crash when opening a world, doesnt look like its from CC&A but its weird if you didnt get it
```
[19:25:58] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/squiddev/cobalt/compiler/CompileException
        at dan200.computercraft.shared.computer.core.ServerContext.<clinit>(ServerContext.java:55) ~[cc-tweaked-282001-4726253.jar:?]
        at dan200.computercraft.shared.CommonHooks.resetState(CommonHooks.java:68) ~[cc-tweaked-282001-4726253.jar:?]
        at dan200.computercraft.shared.CommonHooks.onServerStarting(CommonHooks.java:58) ~[cc-tweaked-282001-4726253.jar:?]
        at dan200.computercraft.shared.ComputerCraft.lambda$init$12(ComputerCraft.java:79) ~[cc-tweaked-282001-4726253.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.2.21+b3afc78b77.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zgh000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:2337) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:646) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.squiddev.cobalt.compiler.CompileException
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 9 more
[19:25:58] [Server thread/ERROR] (Minecraft) This crash report has been saved to: W:\Minecraft\Github\createaddition-fabric\createaddition\run\crash-reports\crash-2023-08-31_19.25.58-server.txt
[19:25:58] [Server thread/INFO] (Minecraft) Stopping server
[19:25:58] [Server thread/INFO] (Minecraft) Saving players
[19:25:58] [Server thread/INFO] (Minecraft) Saving worlds
[19:25:58] [Server thread/ERROR] (Minecraft) Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.getWorldBorder()" because "serverLevel2" is null
        at net.minecraft.server.MinecraftServer.saveAllChunks(MinecraftServer.java:541) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:602) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at net.minecraft.client.server.IntegratedServer.stopServer(IntegratedServer.java:209) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:703) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-merged-project-root-1.20.1-loom.mappings.1_20_1.layered+hash.436717981-v2.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by skippyall** [comment]
Got this crash too when opening from the IDE, but not when building and testing with the jar

**Comment by skippyall** [comment]
Fixed in #651

**Pull request merged**
