### PR TITLE
1.19.2 fabric port & upstream (Completed)

### PR DESCRIPTION
**Pull request by FluffyBumblebees**
the title says it all...

### CODE REVIEW

**Comment by FluffyBumblebees** [comment]
Ok I say that it's mostly done. Just gotta do some testing now

**Comment by mrh0** [comment]
make sure to check all the Issues tagged Fabric, comment on the once that has been fixed and ill close them

**Comment by FluffyBumblebees** [comment]
Alright

**Comment by FluffyBumblebees** [comment]
What the hell was I doing? Anyways, it works now

**Comment by Shazuli** [comment]
It looks like the jar from release 1.19.2-Fabric-Upstream crashes the game when placing down a Steam Engine. Not sure if you've already noticed that but just as a heads-up just in case.

**Comment by mrh0** [comment]
good job 👍 though, target the fabric-1.19.2 branch instead

**Comment by FluffyBumblebees** [comment]
alright

**Comment by FluffyBumblebees** [comment]
There we go

**Review by mrh0 — APPROVED** [review]

**Pull request merged**
