### PR TITLE
Fix dependencies + JEI Compat for fabric

### PR DESCRIPTION
**Pull request by FluffyBumblebees**
It should still be merged so everybody can work on it.

### CODE REVIEW

**Comment by FluffyBumblebees** [comment]
unless someone can help

**Comment by FluffyBumblebees** [comment]
im not having another REI situation

**Comment by FluffyBumblebees** [comment]
Ok it works now

**Review by mrh0 — APPROVED** [review]

**Comment by Chikage0o0** [comment]
@FluffyBumblebees Considering that create also supports EMI, could you add support for EMI? Many thanks!

The recipe tree feature offered by EMI will greatly enhance the gaming experience.
https://modrinth.com/mod/emi

**Comment by FluffyBumblebees** [comment]
I might, depending on various circumstances. But my stance of now is most likely not.

**Pull request merged**
