### PR TITLE
Fabric 1.18.2 (Create 0.5)

### PR DESCRIPTION
**Pull request by FluffyBumblebees**
Okay it's ready to merge now

### CODE REVIEW

**Comment by FluffyBumblebees** [comment]
It doesnt have the REI compat plugins as it needs an entire rework

**Comment by FluffyBumblebees** [comment]
Somebody help with the REI Compat lol. I have a headache

**Comment by FluffyBumblebees** [comment]
It compiiles and boots atleast lmao

**Comment by FluffyBumblebees** [comment]
just gonna make this a draft bc it clearly isnt fully working yet

**Comment by FluffyBumblebees** [comment]
Yeah, I give up! I cannot figure out this REI shit. sorry to whoever really wanted this port, but I just cannot do it.
Gotta wait for AlphaMode ig?

**Comment by FluffyBumblebees** [comment]
Here is a jar for anybody that is impatient: https://github.com/FluffyBumblebees/createaddition/releases/tag/Beta

**Comment by Mikm159** [comment]
There is a serious bug in the latest release file. When I add the current version of mod to the server or local game, the pickaxes become unusable. When only create and createaddition are added, this bug still reappears. I'm sorry for my impoliteness. I'm also sorry for my poor English

> 这是给任何不耐烦的人的罐子：https://github.com/FluffyBumblebees/createaddition/releases/tag/Beta

**Comment by FluffyBumblebees** [comment]
Probably broken loot tables or something. This repo is  a draft so I don't recommend that you use it.

**Comment by Mikm159** [comment]
This problem has been solved. The reason for the problem is that there are redundant item IDS in data\minecraft\tags\blocks\mineable\pickaxe.json. Mod works perfectly, except that you can't use REI to view the recipes of rolling mill

> Probably broken loot tables or something. This repo is a draft so I don't recommend that you use it.

**Comment by FluffyBumblebees** [comment]
https://github.com/FluffyBumblebees/createaddition/releases/tag/Pre-release fixes those mining level problems

**Comment by FluffyBumblebees** [comment]
> This problem has been solved. The reason for the problem is that there are redundant item IDS in data\minecraft\tags\blocks\mineable\pickaxe.json. Mod works perfectly, except that you can't use REI to view the recipes of rolling mill
> 
> > Probably broken loot tables or something. This repo is a draft so I don't recommend that you use it.

The REI thing is intentional, Idk how to fix it. someone who is good at that should help bc im clueless

**Comment by FluffyBumblebees** [comment]
God I hate this. I might be able to get REI working but help is still better.

**Comment by FluffyBumblebees** [comment]
Its over

**Comment by FluffyBumblebees** [comment]
https://github.com/FluffyBumblebees/createaddition/releases/tag/Release
Now with REI Compat

**Comment by mrh0** [comment]
Thanks a lot!

**Pull request merged**
