### PR TITLE
Add sound effects to the mod's electric blocks

### LINKED ISSUE #307: Add buzzing sounds into tesla coil
Adding buzzing sound in tesla coil make the tesla coil feel more real.

### PR DESCRIPTION
**Pull request by nightmarishblue**
Closes #307 and adds:
- Dynamo buzz to alternator and motor.
- Electric crackle to tesla, and a zap when it charges an item or shocks an entity.
- Light charging noise when power is drawn from or added to an accumulator.

There could be improvements to the code and certainly the sound effects. They're taken from freesound.org and pixabay.com and are all Creative Commons, so their use is fine. If I remembered who made which, I would credit them.

### CODE REVIEW

**Comment by mrh0** [comment]
Nice, however id really like to have proper credits to the sound creators, and links to their source before i merge this

**Comment by nightmarishblue** [comment]
I found the sources. You can credit the creators in whatever way you see fit.

https://pixabay.com/sound-effects/electric-zap-001-6374/
The signature shock when a tesla zaps an unsuspecting victim.
https://pixabay.com/sound-effects/075681-electric-shock-33018/
A lighter shock that plays periodically and when the tesla charges an item.
https://pixabay.com/sound-effects/electric-sparks-6130/
The current ambient tesla noise (it could be better).
https://pixabay.com/sound-effects/sparksfly6-27447/
Unused tesla sound. Sounds more like a real tesla coil but it just didn't work right.
https://freesound.org/people/davidkyoku/sounds/157730/
The electric buzz that plays out of dynamos and the accumulator.

**Comment by mrh0** [comment]
Great, ill look over this once i find the time 👍

**Comment by mrh0** [comment]
Excellent work!

**Comment by mrh0** [comment]
I've had multiple reports of a client crash issue with the sounds, see: https://discord.com/channels/806646525605183489/1202937848886595624/1202937848886595624
It seems to only happen for some people but they are all playing on a server

**Comment by nightmarishblue** [comment]
Is there a GitHub issue for this? The channel in the Discord link is only partially loading for me and I'd need to know more about the environment in order to reproduce and diagnose this. I have been able to get the crash report though.

If "RegistryObject not present" is the error message, then I can think of one or two potential issues. It's probably a good start to make sure createaddition's Registry objects are being registered in the correct order, as I've seen similar undefined behaviour occur in large modpacks otherwise.
I don't remember this order off the top of my head because it's not well-documented in Forge, but I think the Block and Item registries go first and then all the other ones go alphabetically.

Anything more than that will need more digging. I will look through the code, but I don't think the problem is inside the AlternatorBlockEntity's tick logic (I'd need to know if this happens with all sounds to be sure). I notice this user has OptiFine installed, so I'd advise they disable it because it could be doing some bad mixins.

**Pull request merged**
