### PR TITLE
Create pl_pl.json

### PR DESCRIPTION
**Pull request by cyerce**
A Polish translation for the Create Crafts & Additions mod

### CODE REVIEW

**Comment by mrh0** [comment]
this pr should not point towards main, 1.19.2/1.20.1 are the active branches. I'll keep this open and fix it manually whenever i do another update

**Review by mrh0 — APPROVED** [review]

**Comment by cyerce** [comment]
> this pr should not point towards main, 1.19.2/1.20.1 are the active branches. I'll keep this open and fix it manually whenever i do another update

Thank you, should I update the pull request to point to 1.20.1?

**Comment by mrh0** [comment]
> > this pr should not point towards main, 1.19.2/1.20.1 are the active branches. I'll keep this open and fix it manually whenever i do another update
> 
> Thank you, should I update the pull request to point to 1.20.1?

sure

**Comment by mrh0** [comment]
added manually 👍

**Pull request closed without merging**
